### ISSUE TITLE
Non-admin users cannot change their passwords

### ISSUE THREAD

**Issue by sterborg** [koninklijke-collective/my_user_management#54] opened 2020-07-20 11:17 UTC
With the extension installed, a non-admin user cannot change his password.
After the change a success flash message appears but the new password is not saved but instead the old password still works.

TYPO3 9.5.19
my_user_management 4.1.0

**Comment by sterborg** [comment] 2020-07-27 07:31
Correction: not all non-admin users have this problem. Users of a usergroup that is allowed to maintain users and usergorups vi my_user_management do not have this problem.

**Comment by sterborg** [comment] 2020-07-31 09:51
Addition: password change is possible, it just needs the correct configuration.

Solution: The usergroup needs the view and change rights for the table be_users. In addition to the exclude_fields you really want to change (password in this case) you have to enable the field **username**. Otherwise you get an error in the log: Attempt to modify table 'be_users' without permission.

So maybe this is not really a bug in this extension but mere a cause of how data changes in be_users are handled.

**Comment by maddy2101** [comment] 2020-08-25 08:13
IMO this is a bug, because the User Settings module, where non-admin users edit their data (like email, password and the like), does not require any edit permissions to be_users table. This is the whole cause the module exists, because it limits the user to their own be_user record, without any possibility to reach for other users records.

So we actually have a bug here, because my_user_management v3 allowed the functionality just fine, but with v4 not only insert and delete are checked for permissions, but also update (which includes changing password).

**Comment by sbuerk** [comment] 2020-08-25 10:31
I think checking the update access on table level is to "early" and prevents the allow the exception that a be user can edit it's own record.

Intstead checking it on table base through the DataHandlerCheckModifyAccessListHookInterface (update, not insert/delete), it would be better to move for update access check to the record based check using TYPO3\CMS\Core\DataHandling\DataHandler::checkRecordUpdateAccess() (and the available hook in there).

This will check for each record in that table. So you can allow it more openly for the current user, but lock it down to "table" wide access configuration if it is not the current be user.

**Comment by maddy2101** [comment] 2020-08-25 13:08
hi guys,

we actually got a core issue here. With v9, the SetupModuleController changed its ways, leading to non-admin user changing their settings not being admin anymore - leading in turn to our issue.

Here is the issue with patch attached: https://forge.typo3.org/issues/92097
It will not be backported to v9 because it is not critical, but you can use the change and put it to your instances. Then all should work as expected.

**Comment by NamelessCoder** [comment] 2020-12-10 15:10
> MO this is a bug, because the User Settings module, where non-admin users edit their data (like email, password and the like), does not require any edit permissions to be_users table. 

I'm afraid this isn't entirely true. The core itself actually does require the exclude field be_users.password to be allowed for the user(-group) or the value is filtered out in DataHandler when processing exclude fields. See https://forge.typo3.org/issues/93049.

The workarounds:

* (with or without my_user_management) Give be_groups user belongs to, edit access to exclude field be_users.password
* (with my_user_management) Give be_groups user belongs to, edit access to table be_users (quite drastic, you should reconsider this requirement that is imposed by the modify tables access hook listsner!)
* (with my_user_management) Give be_groups user belongs to, edit access to be_users.username (this doesn't seem like a reasonable constraint to impose in the table modify access hook listsner but there may be a good reason for this that I'm not aware of)

**Comment by fsuter** [comment] 2021-01-29 09:43
I can confirm the above. There is an issue with my_user_management and an issue with the Core.

For my_user_management, the solution could be to check if the instance of `DataHandler` that we receive as argument in the hook has the `admin` flag forced to "true".

**Comment by fsuter** [comment] 2021-01-29 09:49
Digging one step deeper, there's actually no Core issue. By default the "be_users" table has no exclude fields. It is "my_user_management" which adds the "exclude" flag for all fields of tables "be_users", "be_groups" and "sys_filemounts", thus triggering the problem.
So maybe the solution is just appropriate documentation.

**Comment by bmoex** [comment] 2022-08-05 08:58
This is fixed in TYPO3 10 (https://review.typo3.org/c/Packages/TYPO3.CMS/+/65473).

**Closed by bmoex** 2022-08-05 08:58 UTC
